{
 "title": "1.12 DC/OS Overview Dashboard",
 "description": "Example of an DC/OS Overview dashboard for DC/OS 1.12",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Allocation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_cpus_percent{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_mem_percent{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Disk Allocation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_disk_percent{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "GPU Allocation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_gpus_percent{state=\"leader\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "mesos_master_cpus_percent" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "mesos_master_mem_percent" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "mesos_master_disk_percent" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    { "expr": "mesos_master_gpus_percent" }
   ]
  },
  { "title": "Cluster Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage % (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by(instance)(cpu_usage_system + cpu_usage_user + cpu_usage_guest)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "max by(instance)(mem_active)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Disk Used Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "max by(instance)(disk_used)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GPU Usage % (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "mesos_master_gpus_percent", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Cluster Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Active Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_active{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Unreachable Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_unreachable{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Deactivated Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_inactive{state=\"leader\"}"
    }
   ]
  },
  { "title": "Framework Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Active Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_frameworks_active{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Inactive Frameworks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_frameworks_inactive{state=\"leader\"}"
    }
   ]
  },
  { "title": "Task Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Tasks Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_running{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Tasks Starting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_starting{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Tasks Staging",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_staging{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_failed{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Tasks Lost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_lost{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Tasks Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_tasks_unreachable{state=\"leader\"}"
    }
   ]
  }
 ]
}