{
 "title": "Mesosphere DC/OS Agents Overview",
 "description": "Agents Overview dashboard for DC/OS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_active{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Unreachable Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_unreachable{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Deactivated Agents",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_slaves_inactive{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "CPUs Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_cpus_total{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "CPUs Allocated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_allocator_mesos_resources_cpus_offered_or_allocated{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "CPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(mesos_master_cpus_total{state=\"leader\"} - mesos_allocator_mesos_resources_cpus_offered_or_allocated{state=\"leader\"})"
    }
   ]
  },
  {
   "title": "GPUs Available",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_gpus_total{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "GPUs Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_gpus_used{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_mem_total{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_allocator_mesos_resources_mem_offered_or_allocated{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 6 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_mem_total{state=\"leader\"} - mesos_allocator_mesos_resources_mem_offered_or_allocated{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_disk_total{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Disk Allocated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 8 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_allocator_mesos_resources_disk_offered_or_allocated{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "Disk Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 8 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mesos_master_disk_total{state=\"leader\"} - mesos_allocator_mesos_resources_disk_offered_or_allocated{state=\"leader\"}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "description": "Allocation and utilization",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by(instance)(cpu_usage_system + cpu_usage_user + cpu_usage_guest)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by(instance)(mem_used_percent)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by(instance)(disk_used_percent)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum by(instance)(gpu)" }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "count by(task_name)(task_status_task_running)",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}